# Generated by Django 3.2 on 2024-06-21 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff', models.CharField(max_length=255)),
                ('thumbnail', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('old_price', models.CharField(max_length=50)),
                ('new_price', models.CharField(max_length=50)),
                ('banner', models.CharField(max_length=255)),
                ('display_photo', models.CharField(max_length=255)),
                ('menu', models.CharField(max_length=255)),
                ('star', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('thumbnail', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff', models.CharField(max_length=255)),
                ('item', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('rating', models.CharField(max_length=10)),
                ('thumbnail', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('banner', models.CharField(max_length=255)),
                ('logo', models.CharField(max_length=255)),
                ('delivery_time', models.CharField(max_length=50)),
                ('delivery_fee', models.CharField(max_length=50)),
                ('products', models.ManyToManyField(related_name='stores', to='ecommerce.Product')),
            ],
        ),
        migrations.CreateModel(
            name='SuperCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='ecommerce.category')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='ecommerce.store')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='items',
            field=models.ManyToManyField(related_name='categories', to='ecommerce.Item'),
        ),
    ]
