# Generated by Django 3.2 on 2024-06-21 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='item',
        ),
    ]
