# Generated by Django 3.2 on 2024-06-22 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_evcategory_evitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EVCategory',
        ),
        migrations.DeleteModel(
            name='EVItem',
        ),
    ]
