export const StoreData = [
  {
    id: 1,
    cutoff: "-20%",
    item: "Chicken",
    desc: "Lorem Ipsum",
    rating: "95% (100+)",
    thumbnail: "/lStore1.png",
    name: "Tasty Buggar",
    banner: "/foodStoreBanner.png",
    logo: "/lStoreLogo.png",
    delivery_time: "20-30'",
    delivery_fee: "$100",
    product: [
      {
        id: 1,
        category: "Food",
        icon: "/foodIcon.png",
        item: [
          {
            id: 1,
            cutoff: "-20%",
            thumbnail: "/lStoreFood1.png",
            title: "Lorem Ipsum is a dummy text and a very",
            desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
            old_price: "$120",
            new_price: "$100",
            banner: "/foodPageBanner.png",
            display_photo: "/foodPageDisplayPhoto.png",
            menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
            star: 4,
          },
          {
            id: 2,
            cutoff: "-20%",
            thumbnail: "/lStoreFood2.png",
            title: "Lorem Ipsum is a dummy text and a very",
            desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
            old_price: "$120",
            new_price: "$100",
            banner: "/foodPageBanner.png",
            display_photo: "/foodPageDisplayPhoto.png",
            menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
            star: 5,
          },
          {
            id: 3,
            cutoff: "-20%",
            thumbnail: "/lStoreFood3.png",
            title: "Lorem Ipsum is a dummy text and a very",
            desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
            old_price: "$120",
            new_price: "$100",
            banner: "/foodPageBanner.png",
            display_photo: "/foodPageDisplayPhoto.png",
            menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
            star: 4,
          },
        ],
      },

      {
        id: 2,
        category: "Drinks",
        icon: "/drinksIcon.png",
        item: [
          {
            id: 1,
            cutoff: "-20%",
            thumbnail: "/lStoreDrink1.png",
            title: "Lorem Ipsum is a dummy text and a very",
            desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
            old_price: "$120",
            new_price: "$100",
            banner: "/drinkPageBanner.png",
            display_photo: "/drinkPageDisplayPhoto.png",
            menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
            star: 5,
          },
        ],
      },
    ],
  },

  {
    id: 2,
    cutoff: "-20%",
    item: "Chicken",
    desc: "Lorem Ipsum",
    rating: "95% (100+)",
    thumbnail: "/lStore2.png",
    name: "Chicken Republic",
    banner: "/foodStoreBanner.png",
    logo: "/lStoreLogo.png",
    delivery_time: "20-30'",
    delivery_fee: "$100",
    product: [
      {
        id: 1,
        category: "Food",
        icon: "/foodIcon.png",
        item: [
          {
            id: 1,
            cutoff: "-20%",
            thumbnail: "/lStoreFood1.png",
            title: "Lorem Ipsum is a dummy text and a very",
            desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
            old_price: "$120",
            new_price: "$100",
            banner: "/foodPageBanner.png",
            display_photo: "/foodPageDisplayPhoto.png",
            menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
            star: 5,
          },
          {
            id: 2,
            cutoff: "-20%",
            thumbnail: "/lStoreFood2.png",
            title: "Lorem Ipsum is a dummy text and a very",
            desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
            old_price: "$120",
            new_price: "$100",
            banner: "/foodPageBanner.png",
            display_photo: "/foodPageDisplayPhoto.png",
            menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
            star: 3,
          },
          {
            id: 3,
            cutoff: "-20%",
            thumbnail: "/lStoreFood3.png",
            title: "Lorem Ipsum is a dummy text and a very",
            desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
            old_price: "$120",
            new_price: "$100",
            banner: "/foodPageBanner.png",
            display_photo: "/foodPageDisplayPhoto.png",
            menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
            star: 5,
          },
        ],
      },

      {
        id: 2,
        category: "Drinks",
        icon: "/drinksIcon.png",
        item: [
          {
            id: 1,
            cutoff: "-20%",
            thumbnail: "/lStoreDrink1.png",
            title: "Lorem Ipsum is a dummy text and a very",
            desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
            old_price: "$120",
            new_price: "$100",
            banner: "/drinkPageBanner.png",
            display_photo: "/drinkPageDisplayPhoto.png",
            menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
            star: 5,
          },
        ],
      },
    ],
  },

  {
    id: 3,
    cutoff: "-20%",
    item: "Chicken",
    desc: "Lorem Ipsum",
    rating: "95% (100+)",
    thumbnail: "/lStore3.png",
    name: "Tantalizer",
    banner: "/foodStoreBanner.png",
    logo: "/lStoreLogo.png",
    delivery_time: "20-30'",
    delivery_fee: "$100",
    product: [
      {
        id: 1,
        category: "Food",
        icon: "/foodIcon.png",
        item: [
          {
            id: 1,
            cutoff: "-20%",
            thumbnail: "/lStoreFood1.png",
            title: "Lorem Ipsum is a dummy text and a very",
            desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
            old_price: "$120",
            new_price: "$100",
            banner: "/foodPageBanner.png",
            display_photo: "/foodPageDisplayPhoto.png",
            menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
            star: 5,
          },
          {
            id: 2,
            cutoff: "-20%",
            thumbnail: "/lStoreFood2.png",
            title: "Lorem Ipsum is a dummy text and a very",
            desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
            old_price: "$120",
            new_price: "$100",
            banner: "/foodPageBanner.png",
            display_photo: "/foodPageDisplayPhoto.png",
            menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
            star: 5,
          },
          {
            id: 3,
            cutoff: "-20%",
            thumbnail: "/lStoreFood3.png",
            title: "Lorem Ipsum is a dummy text and a very",
            desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
            old_price: "$120",
            new_price: "$100",
            banner: "/foodPageBanner.png",
            display_photo: "/foodPageDisplayPhoto.png",
            menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
            star: 5,
          },
        ],
      },

      {
        id: 2,
        category: "Drinks",
        icon: "/drinksIcon.png",
        item: [
          {
            id: 1,
            cutoff: "-20%",
            thumbnail: "/lStoreDrink1.png",
            title: "Lorem Ipsum is a dummy text and a very",
            desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
            old_price: "$120",
            new_price: "$100",
            banner: "/drinkPageBanner.png",
            display_photo: "/drinkPageDisplayPhoto.png",
            menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
            star: 5,
          },
        ],
      },
    ],
  },

  {
    id: 4,
    cutoff: "-20%",
    item: "Chicken",
    desc: "Lorem Ipsum",
    rating: "95% (100+)",
    thumbnail: "/lStore4.png",
    name: "LA Spag",
    banner: "/foodStoreBanner.png",
    logo: "/lStoreLogo.png",
    delivery_time: "20-30'",
    delivery_fee: "$100",
    product: [
      {
        id: 1,
        category: "Food",
        icon: "/foodIcon.png",
        item: [
          {
            id: 1,
            cutoff: "-20%",
            thumbnail: "/lStoreFood1.png",
            title: "Lorem Ipsum is a dummy text and a very",
            desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
            old_price: "$120",
            new_price: "$100",
            banner: "/foodPageBanner.png",
            display_photo: "/foodPageDisplayPhoto.png",
            menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
            star: 5,
          },
          {
            id: 2,
            cutoff: "-20%",
            thumbnail: "/lStoreFood2.png",
            title: "Lorem Ipsum is a dummy text and a very",
            desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
            old_price: "$120",
            new_price: "$100",
            banner: "/foodPageBanner.png",
            display_photo: "/foodPageDisplayPhoto.png",
            menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
            star: 5,
          },
          {
            id: 3,
            cutoff: "-20%",
            thumbnail: "/lStoreFood3.png",
            title: "Lorem Ipsum is a dummy text and a very",
            desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
            old_price: "$120",
            new_price: "$100",
            banner: "/foodPageBanner.png",
            display_photo: "/foodPageDisplayPhoto.png",
            menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
            star: 5,
          },
        ],
      },

      {
        id: 2,
        category: "Drinks",
        icon: "/drinksIcon.png",
        item: [
          {
            id: 1,
            cutoff: "-20%",
            thumbnail: "/lStoreDrink1.png",
            title: "Lorem Ipsum is a dummy text and a very",
            desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
            old_price: "$120",
            new_price: "$100",
            banner: "/drinkPageBanner.png",
            display_photo: "/drinkPageDisplayPhoto.png",
            menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
            star: 5,
          },
        ],
      },
    ],
  },

  {
    id: 5,
    cutoff: "-20%",
    item: "Chicken",
    desc: "Lorem Ipsum",
    rating: "95% (100+)",
    thumbnail: "/lStore5.png",
    name: "Chi Cherry",
    banner: "/foodStoreBanner.png",
    logo: "/lStoreLogo.png",
    delivery_time: "20-30'",
    delivery_fee: "$100",
    product: [
      {
        id: 1,
        category: "Food",
        icon: "/foodIcon.png",
        item: [
          {
            id: 1,
            cutoff: "-20%",
            thumbnail: "/lStoreFood1.png",
            title: "Lorem Ipsum is a dummy text and a very",
            desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
            old_price: "$120",
            new_price: "$100",
            banner: "/foodPageBanner.png",
            display_photo: "/foodPageDisplayPhoto.png",
            menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
            star: 4,
          },
          {
            id: 2,
            cutoff: "-20%",
            thumbnail: "/lStoreFood2.png",
            title: "Lorem Ipsum is a dummy text and a very",
            desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
            old_price: "$120",
            new_price: "$100",
            banner: "/foodPageBanner.png",
            display_photo: "/foodPageDisplayPhoto.png",
            menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
            star: 5,
          },
          {
            id: 3,
            cutoff: "-20%",
            thumbnail: "/lStoreFood3.png",
            title: "Lorem Ipsum is a dummy text and a very",
            desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
            old_price: "$120",
            new_price: "$100",
            banner: "/foodPageBanner.png",
            display_photo: "/foodPageDisplayPhoto.png",
            menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
            star: 4,
          },
        ],
      },

      {
        id: 2,
        category: "Drinks",
        icon: "/drinksIcon.png",
        item: [
          {
            id: 1,
            cutoff: "-20%",
            thumbnail: "/lStoreDrink1.png",
            title: "Lorem Ipsum is a dummy text and a very",
            desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
            old_price: "$120",
            new_price: "$100",
            banner: "/drinkPageBanner.png",
            display_photo: "/drinkPageDisplayPhoto.png",
            menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
            star: 5,
          },
        ],
      },
    ],
  },

  {
    id: 6,
    cutoff: "-20%",
    item: "Chicken",
    desc: "Lorem Ipsum",
    rating: "95% (100+)",
    thumbnail: "/lStore6.png",
    name: "Tasty Fingers",
    banner: "/foodStoreBanner.png",
    logo: "/lStoreLogo.png",
    delivery_time: "20-30'",
    delivery_fee: "$100",
    product: [
      {
        id: 1,
        category: "Food",
        icon: "/foodIcon.png",
        item: [
          {
            id: 1,
            cutoff: "-20%",
            thumbnail: "/lStoreFood1.png",
            title: "Lorem Ipsum is a dummy text and a very",
            desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
            old_price: "$120",
            new_price: "$100",
            banner: "/foodPageBanner.png",
            display_photo: "/foodPageDisplayPhoto.png",
            menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
            star: 5,
          },
          {
            id: 2,
            cutoff: "-20%",
            thumbnail: "/lStoreFood2.png",
            title: "Lorem Ipsum is a dummy text and a very",
            desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
            old_price: "$120",
            new_price: "$100",
            banner: "/foodPageBanner.png",
            display_photo: "/foodPageDisplayPhoto.png",
            menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
            star: 5,
          },
          {
            id: 3,
            cutoff: "-20%",
            thumbnail: "/lStoreFood3.png",
            title: "Lorem Ipsum is a dummy text and a very",
            desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
            old_price: "$120",
            new_price: "$100",
            banner: "/foodPageBanner.png",
            display_photo: "/foodPageDisplayPhoto.png",
            menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
            star: 3,
          },
        ],
      },

      {
        id: 2,
        category: "Drinks",
        icon: "/drinksIcon.png",
        item: [
          {
            id: 1,
            cutoff: "-20%",
            thumbnail: "/lStoreDrink1.png",
            title: "Lorem Ipsum is a dummy text and a very",
            desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
            old_price: "$120",
            new_price: "$100",
            banner: "/drinkPageBanner.png",
            display_photo: "/drinkPageDisplayPhoto.png",
            menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
            star: 5,
          },
        ],
      },
    ],
  },

  {
    id: 7,
    cutoff: "-20%",
    item: "Chicken",
    desc: "Lorem Ipsum",
    rating: "95% (100+)",
    thumbnail: "/lStore7.png",
    name: "TC Buggar",
    banner: "/foodStoreBanner.png",
    logo: "/lStoreLogo.png",
    delivery_time: "20-30'",
    delivery_fee: "$100",
    product: [
      {
        id: 1,
        category: "Food",
        icon: "/foodIcon.png",
        item: [
          {
            id: 1,
            cutoff: "-20%",
            thumbnail: "/lStoreFood1.png",
            title: "Lorem Ipsum is a dummy text and a very",
            desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
            old_price: "$120",
            new_price: "$100",
            banner: "/foodPageBanner.png",
            display_photo: "/foodPageDisplayPhoto.png",
            menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
            star: 4,
          },
          {
            id: 2,
            cutoff: "-20%",
            thumbnail: "/lStoreFood2.png",
            title: "Lorem Ipsum is a dummy text and a very",
            desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
            old_price: "$120",
            new_price: "$100",
            banner: "/foodPageBanner.png",
            display_photo: "/foodPageDisplayPhoto.png",
            menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
            star: 5,
          },
          {
            id: 3,
            cutoff: "-20%",
            thumbnail: "/lStoreFood3.png",
            title: "Lorem Ipsum is a dummy text and a very",
            desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
            old_price: "$120",
            new_price: "$100",
            banner: "/foodPageBanner.png",
            display_photo: "/foodPageDisplayPhoto.png",
            menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
            star: 5,
          },
        ],
      },

      {
        id: 2,
        category: "Drinks",
        icon: "/drinksIcon.png",
        item: [
          {
            id: 1,
            cutoff: "-20%",
            thumbnail: "/lStoreDrink1.png",
            title: "Lorem Ipsum is a dummy text and a very",
            desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
            old_price: "$120",
            new_price: "$100",
            banner: "/drinkPageBanner.png",
            display_photo: "/drinkPageDisplayPhoto.png",
            menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
            star: 5,
          },
        ],
      },
    ],
  },

  {
    id: 8,
    cutoff: "-20%",
    item: "Chicken",
    desc: "Lorem Ipsum",
    rating: "95% (100+)",
    thumbnail: "/lStore8.png",
    name: "Pallet n' Drapes",
    banner: "/foodStoreBanner.png",
    logo: "/lStoreLogo.png",
    delivery_time: "20-30'",
    delivery_fee: "$100",
    product: [
      {
        id: 1,
        category: "Food",
        icon: "/foodIcon.png",
        item: [
          {
            id: 1,
            cutoff: "-20%",
            thumbnail: "/lStoreFood1.png",
            title: "Lorem Ipsum is a dummy text and a very",
            desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
            old_price: "$120",
            new_price: "$100",
            banner: "/foodPageBanner.png",
            display_photo: "/foodPageDisplayPhoto.png",
            menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
            star: 5,
          },
          {
            id: 2,
            cutoff: "-20%",
            thumbnail: "/lStoreFood2.png",
            title: "Lorem Ipsum is a dummy text and a very",
            desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
            old_price: "$120",
            new_price: "$100",
            banner: "/foodPageBanner.png",
            display_photo: "/foodPageDisplayPhoto.png",
            menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
            star: 5,
          },
          {
            id: 3,
            cutoff: "-20%",
            thumbnail: "/lStoreFood3.png",
            title: "Lorem Ipsum is a dummy text and a very",
            desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
            old_price: "$120",
            new_price: "$100",
            banner: "/foodPageBanner.png",
            display_photo: "/foodPageDisplayPhoto.png",
            menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
            star: 5,
          },
        ],
      },

      {
        id: 2,
        category: "Drinks",
        icon: "/drinksIcon.png",
        item: [
          {
            id: 1,
            cutoff: "-20%",
            thumbnail: "/lStoreDrink1.png",
            title: "Lorem Ipsum is a dummy text and a very",
            desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
            old_price: "$120",
            new_price: "$100",
            banner: "/drinkPageBanner.png",
            display_photo: "/drinkPageDisplayPhoto.png",
            menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
            star: 5,
          },
        ],
      },
    ],
  },
];

export const FoodData = {
  categories: [
    { name: "Chicken", icon: "/cChicken.png" },
    { name: "Soup", icon: "/cSoup.png" },
    { name: "Rice", icon: "/cRice.png" },
    { name: "Pasta", icon: "/cPasta.png" },
    { name: "Vegetable", icon: "/cVegetable.png" },
  ],
  stores: [
    {
      id: 1,
      cutoff: "-20%",
      item: "Chicken",
      desc: "Lorem Ipsum",
      rating: "95% (100+)",
      thumbnail: "/lStore1.png",
      name: "Tasty Buggar",
      banner: "/foodStoreBanner.png",
      logo: "/lStoreLogo.png",
      delivery_time: "20-30'",
      delivery_fee: "$100",
      product: [
        {
          id: 1,
          category: "Food",
          icon: "/foodIcon.png",
          item: [
            {
              id: 1,
              cutoff: "-20%",
              thumbnail: "/lStoreFood1.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/foodPageBanner.png",
              display_photo: "/foodPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },
            {
              id: 2,
              cutoff: "-20%",
              thumbnail: "/lStoreFood2.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/foodPageBanner.png",
              display_photo: "/foodPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 5,
            },
            {
              id: 3,
              cutoff: "-20%",
              thumbnail: "/lStoreFood3.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/foodPageBanner.png",
              display_photo: "/foodPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },
          ],
        },

        {
          id: 2,
          category: "Drinks",
          icon: "/drinksIcon.png",
          item: [
            {
              id: 1,
              cutoff: "-20%",
              thumbnail: "/lStoreDrink1.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 5,
            },
          ],
        },
      ],
    },

    {
      id: 2,
      cutoff: "-20%",
      item: "Soups",
      desc: "Lorem Ipsum",
      rating: "95% (100+)",
      thumbnail: "/lStore2.png",
      name: "Chicken Republic",
      banner: "/foodStoreBanner.png",
      logo: "/lStoreLogo.png",
      delivery_time: "20-30'",
      delivery_fee: "$100",

      product: [
        {
          id: 1,
          category: "Food",
          icon: "/foodIcon.png",
          item: [
            {
              id: 1,
              cutoff: "-20%",
              thumbnail: "/lStoreFood1.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/foodPageBanner.png",
              display_photo: "/foodPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 5,
            },
            {
              id: 2,
              cutoff: "-20%",
              thumbnail: "/lStoreFood2.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/foodPageBanner.png",
              display_photo: "/foodPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 3,
            },
            {
              id: 3,
              cutoff: "-20%",
              thumbnail: "/lStoreFood3.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/foodPageBanner.png",
              display_photo: "/foodPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 5,
            },
          ],
        },

        {
          id: 2,
          category: "Drinks",
          icon: "/drinksIcon.png",
          item: [
            {
              id: 1,
              cutoff: "-20%",
              thumbnail: "/lStoreDrink1.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 5,
            },
          ],
        },
      ],
    },

    {
      id: 3,
      cutoff: "-20%",
      item: "Burgers",
      desc: "Lorem Ipsum",
      rating: "95% (100+)",
      thumbnail: "/lStore3.png",
      name: "Tantalizer",
      banner: "/foodStoreBanner.png",
      logo: "/lStoreLogo.png",
      delivery_time: "20-30'",
      delivery_fee: "$100",
      product: [
        {
          id: 1,
          category: "Food",
          icon: "/foodIcon.png",
          item: [
            {
              id: 1,
              cutoff: "-20%",
              thumbnail: "/lStoreFood1.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/foodPageBanner.png",
              display_photo: "/foodPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 5,
            },
            {
              id: 2,
              cutoff: "-20%",
              thumbnail: "/lStoreFood2.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/foodPageBanner.png",
              display_photo: "/foodPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 5,
            },
            {
              id: 3,
              cutoff: "-20%",
              thumbnail: "/lStoreFood3.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/foodPageBanner.png",
              display_photo: "/foodPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 5,
            },
          ],
        },

        {
          id: 2,
          category: "Drinks",
          icon: "/drinksIcon.png",
          item: [
            {
              id: 1,
              cutoff: "-20%",
              thumbnail: "/lStoreDrink1.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 5,
            },
          ],
        },
      ],
    },

    {
      id: 4,
      cutoff: "-20%",
      item: "Chicken",
      desc: "Lorem Ipsum",
      rating: "95% (100+)",
      thumbnail: "/lStore4.png",
      name: "LA Spag",
      banner: "/foodStoreBanner.png",
      logo: "/lStoreLogo.png",
      delivery_time: "20-30'",
      delivery_fee: "$100",
      product: [
        {
          id: 1,
          category: "Food",
          icon: "/foodIcon.png",
          item: [
            {
              id: 1,
              cutoff: "-20%",
              thumbnail: "/lStoreFood1.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/foodPageBanner.png",
              display_photo: "/foodPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 5,
            },
            {
              id: 2,
              cutoff: "-20%",
              thumbnail: "/lStoreFood2.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/foodPageBanner.png",
              display_photo: "/foodPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 5,
            },
            {
              id: 3,
              cutoff: "-20%",
              thumbnail: "/lStoreFood3.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/foodPageBanner.png",
              display_photo: "/foodPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 5,
            },
          ],
        },

        {
          id: 2,
          category: "Drinks",
          icon: "/drinksIcon.png",
          item: [
            {
              id: 1,
              cutoff: "-20%",
              thumbnail: "/lStoreDrink1.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 5,
            },
          ],
        },
      ],
    },
  ],
};

export const DrinksData = {
  categories: [
    { name: "Wine", icon: "/cWine.png" },
    { name: "Beer", icon: "/cBeer.png" },
    { name: "Soda", icon: "/cSoda.png" },
    { name: "Water", icon: "/cWater.png" },
    { name: "Soft", icon: "/cSoft.png" },
  ],
  stores: [
    {
      id: 1,
      cutoff: "-20%",
      item: "Chicken",
      desc: "Lorem Ipsum",
      rating: "95% (100+)",
      thumbnail: "/dStore1.png",
      name: "Tasty Buggar",
      banner: "/dStoreBanner.png",
      logo: "/dStoreLogo.png",
      delivery_time: "20-30'",
      delivery_fee: "$100",
      product: [
        {
          id: 1,
          category: "Wine",
          icon: "/wineIcon.png",
          item: [
            {
              name: "Lorem",
              id: 1,
              cutoff: "-20%",
              thumbnail: "/dStoreWine1.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },
            {
              name: "Lorem",
              id: 2,
              cutoff: "-20%",
              thumbnail: "/dStoreWine2.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 5,
            },
            {
              name: "Lorem",
              id: 3,
              cutoff: "-20%",
              thumbnail: "/dStoreWine3.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },

            {
              name: "Lorem",
              id: 4,
              cutoff: "-20%",
              thumbnail: "/dStoreWine4.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },
            {
              name: "Lorem",
              id: 5,
              cutoff: "-20%",
              thumbnail: "/dStoreWine5.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 5,
            },
            {
              name: "Lorem",
              id: 6,
              cutoff: "-20%",
              thumbnail: "/dStoreWine6.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },

            {
              name: "Lorem",
              id: 7,
              cutoff: "-20%",
              thumbnail: "/dStoreWine7.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/foodPageBanner.png",
              display_photo: "/foodPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },
            {
              name: "Lorem",
              id: 8,
              cutoff: "-20%",
              thumbnail: "/dStoreWine8.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/foodPageBanner.png",
              display_photo: "/foodPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 5,
            },
            {
              name: "Lorem",
              id: 9,
              cutoff: "-20%",
              thumbnail: "/dStoreWine9.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/foodPageBanner.png",
              display_photo: "/foodPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },

            {
              name: "Lorem",
              id: 10,
              cutoff: "-20%",
              thumbnail: "/dStoreWine10.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },
            {
              name: "Lorem",
              id: 11,
              cutoff: "-20%",
              thumbnail: "/dStoreWine11.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 5,
            },
            {
              name: "Lorem",
              id: 12,
              cutoff: "-20%",
              thumbnail: "/dStoreWine12.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },
          ],
        },

        {
          id: 2,
          category: "Coffee",
          icon: "/coffeeIcon.png",
          item: [
            {
              name: "Lorem",
              id: 1,
              cutoff: "-20%",
              thumbnail: "/dStoreCoffee1.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$130",
              new_price: "$110",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 5,
            },

            {
              name: "Lorem",
              id: 2,
              cutoff: "-20%",
              thumbnail: "/dStoreCoffee2.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },

            {
              name: "Lorem",
              id: 3,
              cutoff: "-20%",
              thumbnail: "/dStoreCoffee3.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$150",
              new_price: "$125",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },
          ],
        },
      ],
    },
    {
      id: 2,
      cutoff: "-20%",
      item: "Chicken",
      desc: "Lorem Ipsum",
      rating: "95% (100+)",
      thumbnail: "/dStore2.png",
      name: "Tasty Buggar",
      banner: "/dStoreBanner.png",
      logo: "/dStoreLogo.png",
      delivery_time: "20-30'",
      delivery_fee: "$100",
      product: [
        {
          id: 1,
          category: "Wine",
          icon: "/wineIcon.png",
          item: [
            {
              name: "Lorem",
              id: 1,
              cutoff: "-20%",
              thumbnail: "/dStoreWine1.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },
            {
              name: "Lorem",
              id: 2,
              cutoff: "-20%",
              thumbnail: "/dStoreWine2.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 5,
            },
            {
              name: "Lorem",
              id: 3,
              cutoff: "-20%",
              thumbnail: "/dStoreWine3.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },

            {
              name: "Lorem",
              id: 4,
              cutoff: "-20%",
              thumbnail: "/dStoreWine4.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },
            {
              name: "Lorem",
              id: 5,
              cutoff: "-20%",
              thumbnail: "/dStoreWine5.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 5,
            },
            {
              name: "Lorem",
              id: 6,
              cutoff: "-20%",
              thumbnail: "/dStoreWine6.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },

            {
              name: "Lorem",
              id: 7,
              cutoff: "-20%",
              thumbnail: "/dStoreWine7.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/foodPageBanner.png",
              display_photo: "/foodPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },
            {
              name: "Lorem",
              id: 8,
              cutoff: "-20%",
              thumbnail: "/dStoreWine8.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/foodPageBanner.png",
              display_photo: "/foodPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 5,
            },
            {
              name: "Lorem",
              id: 9,
              cutoff: "-20%",
              thumbnail: "/dStoreWine9.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/foodPageBanner.png",
              display_photo: "/foodPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },

            {
              name: "Lorem",
              id: 10,
              cutoff: "-20%",
              thumbnail: "/dStoreWine10.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },
            {
              name: "Lorem",
              id: 11,
              cutoff: "-20%",
              thumbnail: "/dStoreWine11.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 5,
            },
            {
              name: "Lorem",
              id: 12,
              cutoff: "-20%",
              thumbnail: "/dStoreWine12.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },
          ],
        },

        {
          id: 2,
          category: "Coffee",
          icon: "/coffeeIcon.png",
          item: [
            {
              name: "Lorem",
              id: 1,
              cutoff: "-20%",
              thumbnail: "/dStoreCoffee1.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$130",
              new_price: "$110",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 5,
            },

            {
              name: "Lorem",
              id: 2,
              cutoff: "-20%",
              thumbnail: "/dStoreCoffee2.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },

            {
              name: "Lorem",
              id: 3,
              cutoff: "-20%",
              thumbnail: "/dStoreCoffee3.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$150",
              new_price: "$125",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },
          ],
        },
      ],
    },

    {
      id: 3,
      cutoff: "-20%",
      item: "Chicken",
      desc: "Lorem Ipsum",
      rating: "95% (100+)",
      thumbnail: "/dStore3.png",
      name: "Tasty Buggar",
      banner: "/dStoreBanner.png",
      logo: "/dStoreLogo.png",
      delivery_time: "20-30'",
      delivery_fee: "$100",
      product: [
        {
          id: 1,
          category: "Wine",
          icon: "/wineIcon.png",
          item: [
            {
              name: "Lorem",
              id: 1,
              cutoff: "-20%",
              thumbnail: "/dStoreWine1.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },
            {
              name: "Lorem",
              id: 2,
              cutoff: "-20%",
              thumbnail: "/dStoreWine2.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 5,
            },
            {
              name: "Lorem",
              id: 3,
              cutoff: "-20%",
              thumbnail: "/dStoreWine3.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },

            {
              name: "Lorem",
              id: 4,
              cutoff: "-20%",
              thumbnail: "/dStoreWine4.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },
            {
              name: "Lorem",
              id: 5,
              cutoff: "-20%",
              thumbnail: "/dStoreWine5.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 5,
            },
            {
              name: "Lorem",
              id: 6,
              cutoff: "-20%",
              thumbnail: "/dStoreWine6.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },

            {
              name: "Lorem",
              id: 7,
              cutoff: "-20%",
              thumbnail: "/dStoreWine7.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/foodPageBanner.png",
              display_photo: "/foodPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },
            {
              name: "Lorem",
              id: 8,
              cutoff: "-20%",
              thumbnail: "/dStoreWine8.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/foodPageBanner.png",
              display_photo: "/foodPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 5,
            },
            {
              name: "Lorem",
              id: 9,
              cutoff: "-20%",
              thumbnail: "/dStoreWine9.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/foodPageBanner.png",
              display_photo: "/foodPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },

            {
              name: "Lorem",
              id: 10,
              cutoff: "-20%",
              thumbnail: "/dStoreWine10.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },
            {
              name: "Lorem",
              id: 11,
              cutoff: "-20%",
              thumbnail: "/dStoreWine11.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 5,
            },
            {
              name: "Lorem",
              id: 12,
              cutoff: "-20%",
              thumbnail: "/dStoreWine12.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },
          ],
        },

        {
          id: 2,
          category: "Coffee",
          icon: "/coffeeIcon.png",
          item: [
            {
              name: "Lorem",
              id: 1,
              cutoff: "-20%",
              thumbnail: "/dStoreCoffee1.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$130",
              new_price: "$110",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 5,
            },

            {
              name: "Lorem",
              id: 2,
              cutoff: "-20%",
              thumbnail: "/dStoreCoffee2.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },

            {
              name: "Lorem",
              id: 3,
              cutoff: "-20%",
              thumbnail: "/dStoreCoffee3.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$150",
              new_price: "$125",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },
          ],
        },
      ],
    },
    {
      id: 4,
      cutoff: "-20%",
      item: "Chicken",
      desc: "Lorem Ipsum",
      rating: "95% (100+)",
      thumbnail: "/dStore4.png",
      name: "Tasty Buggar",
      banner: "/dStoreBanner.png",
      logo: "/dStoreLogo.png",
      delivery_time: "20-30'",
      delivery_fee: "$100",
      product: [
        {
          id: 1,
          category: "Wine",
          icon: "/wineIcon.png",
          item: [
            {
              name: "Lorem",
              id: 1,
              cutoff: "-20%",
              thumbnail: "/dStoreWine1.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },
            {
              name: "Lorem",
              id: 2,
              cutoff: "-20%",
              thumbnail: "/dStoreWine2.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 5,
            },
            {
              name: "Lorem",
              id: 3,
              cutoff: "-20%",
              thumbnail: "/dStoreWine3.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },

            {
              name: "Lorem",
              id: 4,
              cutoff: "-20%",
              thumbnail: "/dStoreWine4.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },
            {
              name: "Lorem",
              id: 5,
              cutoff: "-20%",
              thumbnail: "/dStoreWine5.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 5,
            },
            {
              name: "Lorem",
              id: 6,
              cutoff: "-20%",
              thumbnail: "/dStoreWine6.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },

            {
              name: "Lorem",
              id: 7,
              cutoff: "-20%",
              thumbnail: "/dStoreWine7.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/foodPageBanner.png",
              display_photo: "/foodPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },
            {
              name: "Lorem",
              id: 8,
              cutoff: "-20%",
              thumbnail: "/dStoreWine8.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/foodPageBanner.png",
              display_photo: "/foodPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 5,
            },
            {
              name: "Lorem",
              id: 9,
              cutoff: "-20%",
              thumbnail: "/dStoreWine9.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/foodPageBanner.png",
              display_photo: "/foodPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },

            {
              name: "Lorem",
              id: 10,
              cutoff: "-20%",
              thumbnail: "/dStoreWine10.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },
            {
              name: "Lorem",
              id: 11,
              cutoff: "-20%",
              thumbnail: "/dStoreWine11.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 5,
            },
            {
              name: "Lorem",
              id: 12,
              cutoff: "-20%",
              thumbnail: "/dStoreWine12.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },
          ],
        },

        {
          id: 2,
          category: "Coffee",
          icon: "/coffeeIcon.png",
          item: [
            {
              name: "Lorem",
              id: 1,
              cutoff: "-20%",
              thumbnail: "/dStoreCoffee1.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$130",
              new_price: "$110",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 5,
            },

            {
              name: "Lorem",
              id: 2,
              cutoff: "-20%",
              thumbnail: "/dStoreCoffee2.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$120",
              new_price: "$100",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },

            {
              name: "Lorem",
              id: 3,
              cutoff: "-20%",
              thumbnail: "/dStoreCoffee3.png",
              title: "Lorem Ipsum is a dummy text and a very",
              desc: "Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text, Lorem Ipsum is a dummy text and a very dummy text Lorem Ipsum is a dummy text....Lorem Ipsum is a dummy text and a very dummy text ",
              old_price: "$150",
              new_price: "$125",
              banner: "/drinkPageBanner.png",
              display_photo: "/drinkPageDisplayPhoto.png",
              menu: "Lorem Ipsum is a dummy text + babecue chicken + cocacola",
              star: 4,
            },
          ],
        },
      ],
    },
  ],
};