# Generated by Django 3.2 on 2024-06-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EVCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EVItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff', models.CharField(max_length=255)),
                ('thumbnail', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('old_price', models.CharField(max_length=50)),
                ('new_price', models.CharField(max_length=50)),
                ('banner', models.CharField(max_length=255)),
                ('display_photo', models.CharField(max_length=255)),
                ('menu', models.CharField(max_length=255)),
                ('star', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EVStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('rating', models.CharField(max_length=10)),
                ('thumbnail', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('banner', models.CharField(max_length=255)),
                ('logo', models.CharField(max_length=255)),
                ('delivery_time', models.CharField(max_length=50)),
                ('delivery_fee', models.CharField(max_length=50)),
                ('category', models.ManyToManyField(related_name='stores', to='ev.EVCategory')),
            ],
        ),
        migrations.CreateModel(
            name='EVSuperCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('store', models.ManyToManyField(related_name='store', to='ev.EVStore')),
            ],
        ),
        migrations.AddField(
            model_name='evcategory',
            name='items',
            field=models.ManyToManyField(related_name='categories', to='ev.EVItem'),
        ),
    ]
