# Generated by Django 3.2 on 2024-06-23 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EVCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EVItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff', models.CharField(max_length=255)),
                ('thumbnail', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('old_price', models.CharField(max_length=50)),
                ('new_price', models.CharField(max_length=50)),
                ('banner', models.CharField(max_length=255)),
                ('display_photo', models.CharField(max_length=255)),
                ('menu', models.CharField(max_length=255)),
                ('star', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EVStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('rating', models.CharField(max_length=10)),
                ('thumbnail', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('banner', models.CharField(max_length=255)),
                ('logo', models.CharField(max_length=255)),
                ('delivery_time', models.CharField(max_length=50)),
                ('delivery_fee', models.CharField(max_length=50)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ev.evcategory')),
            ],
        ),
        migrations.CreateModel(
            name='EVSuperCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ev.evstore')),
            ],
        ),
        migrations.AddField(
            model_name='evcategory',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ev.evitem'),
        ),
    ]
