# Generated by Django 3.2 on 2024-06-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ev', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evcategory',
            name='items',
        ),
        migrations.AddField(
            model_name='evcategory',
            name='items',
            field=models.ManyToManyField(related_name='categories', to='ev.EVItem'),
        ),
        migrations.RemoveField(
            model_name='evstore',
            name='category',
        ),
        migrations.AddField(
            model_name='evstore',
            name='category',
            field=models.ManyToManyField(related_name='stores', to='ev.EVCategory'),
        ),
        migrations.RemoveField(
            model_name='evsupercategory',
            name='store',
        ),
        migrations.AddField(
            model_name='evsupercategory',
            name='store',
            field=models.ManyToManyField(related_name='store', to='ev.EVStore'),
        ),
    ]
