# Generated by Django 3.2 on 2024-06-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ev', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evitem',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
