# Generated by Django 3.2 on 2024-06-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ev', '0002_alter_evitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evcategory',
            name='items',
            field=models.ManyToManyField(related_name='categories', to='ev.EVItem'),
        ),
        migrations.AlterField(
            model_name='evitem',
            name='description',
            field=models.TextField(),
        ),
    ]
