# Generated by Django 3.2 on 2024-06-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ev', '0003_auto_20240622_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evcategory',
            name='items',
            field=models.ManyToManyField(related_name='items', to='ev.EVItem'),
        ),
    ]
