# Generated by Django 3.2 on 2024-06-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ev', '0004_alter_evcategory_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='EVStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('category', models.ManyToManyField(related_name='stores', to='ev.EVCategory')),
            ],
        ),
        migrations.CreateModel(
            name='EVSuperCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('store', models.ManyToManyField(related_name='store', to='ev.EVStore')),
            ],
        ),
    ]
